export const ORDER_STATUS = {
    REGISTERED: 'REGISTERED',
    DELIVERING_TO_FACTORY: 'DELIVERING_TO_FACTORY', // New status
    PROCESSING: 'PROCESSING',
    TRANSFERRED_TO_SHOP: 'TRANSFERRED_TO_SHOP',
    DELIVERING: 'DELIVERING',
    COMPLETED: 'COMPLETED',
    REVIEW_NEEDED: 'REVIEW_NEEDED',
} as const;

export type OrderStatus = keyof typeof ORDER_STATUS;

export const ORDER_STATUS_LABELS: Record<OrderStatus, string> = {
    [ORDER_STATUS.REGISTERED]: 'قيد التسجيل',
    [ORDER_STATUS.DELIVERING_TO_FACTORY]: 'قيد التسليم للمصنع',
    [ORDER_STATUS.PROCESSING]: 'قيد التجهيز',
    [ORDER_STATUS.TRANSFERRED_TO_SHOP]: 'جاهز للاستلام',
    [ORDER_STATUS.DELIVERING]: 'قيد التسليم',
    [ORDER_STATUS.COMPLETED]: 'مكتمل',
    [ORDER_STATUS.REVIEW_NEEDED]: 'مراجعة مطلوبة',
};

export const ORDER_STATUS_COLORS: Record<OrderStatus, string> = {
    [ORDER_STATUS.REGISTERED]: 'bg-zinc-100 text-zinc-600',
    [ORDER_STATUS.DELIVERING_TO_FACTORY]: 'bg-orange-100 text-orange-600',
    [ORDER_STATUS.PROCESSING]: 'bg-amber-100 text-amber-600',
    [ORDER_STATUS.TRANSFERRED_TO_SHOP]: 'bg-indigo-100 text-indigo-600',
    [ORDER_STATUS.DELIVERING]: 'bg-purple-100 text-purple-600',
    [ORDER_STATUS.COMPLETED]: 'bg-green-100 text-green-600',
    [ORDER_STATUS.REVIEW_NEEDED]: 'bg-red-100 text-red-600',
};

export const FACILITY_TYPE = {
    FACTORY: 'FACTORY',
    SHOP: 'SHOP',
} as const;

export type FacilityType = keyof typeof FACILITY_TYPE;

export const ALLOWED_TRANSITIONS: Record<string, string[]> = {
    [ORDER_STATUS.REGISTERED]: [ORDER_STATUS.DELIVERING_TO_FACTORY, ORDER_STATUS.REVIEW_NEEDED],
    [ORDER_STATUS.DELIVERING_TO_FACTORY]: [ORDER_STATUS.PROCESSING, ORDER_STATUS.REVIEW_NEEDED],
    // [ORDER_STATUS.TRANSFERRED_TO_FACTORY]: [], // Deprecated
    [ORDER_STATUS.PROCESSING]: [ORDER_STATUS.TRANSFERRED_TO_SHOP, ORDER_STATUS.REVIEW_NEEDED],
    [ORDER_STATUS.TRANSFERRED_TO_SHOP]: [ORDER_STATUS.DELIVERING, ORDER_STATUS.COMPLETED, ORDER_STATUS.REVIEW_NEEDED],
    [ORDER_STATUS.DELIVERING]: [ORDER_STATUS.COMPLETED, ORDER_STATUS.TRANSFERRED_TO_SHOP, ORDER_STATUS.REVIEW_NEEDED],
    [ORDER_STATUS.REVIEW_NEEDED]: [ORDER_STATUS.REGISTERED, ORDER_STATUS.PROCESSING, ORDER_STATUS.DELIVERING_TO_FACTORY], // Updated to valid return points
    [ORDER_STATUS.COMPLETED]: [] // Terminal state
};
